apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}

        ports:
        - containerPort: {{ .Values.postgres.port }}

        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: DB_NAME

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: DB_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: DB_PASSWORD
