apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
  namespace: {{ .Values.namespace }}
stringData:
  DB_USER: {{ .Values.secret.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}
type: Opaque
