namespace: go-web-app

replicaCount: 2

image:
  repository: 814636798023.dkr.ecr.ap-south-2.amazonaws.com/employee-api
  tag: "407335d71a91e7c2093e3e41953fb5813532c5fb"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

config:
  PORT: "8080"
  DB_HOST: employee-api-db.c1awosg0a7it.ap-south-2.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: postgres

secret:
  DB_USER: postgres
  DB_PASSWORD: Postgres123

postgres:
  image: postgres:16
  port: 5432
  replicaCount: 1

ingress:
  enabled: true
  className: nginx
  path: /
